import LocalizedStrings from 'react-native-localization'

export const localStrings = new LocalizedStrings({
  en: {
    email: 'e-mail',
    login_title: 'Yad Tamar',
    password: 'Password',
    password_confirmation: 'Confirm password',
    profile: 'Profile',
    login: 'login',
    create_family: 'Create family',
    welcome_text: 'Welcome to',
    my_families: 'My families',
    members_count: 'members',
    name_the_family: 'Name the family',
    prompt_the_family: 'for example: Smith',
    phone_number: 'Phone number',
    last_name: 'Last name',
    volunteers: 'Volunteers',
    add_volunteer: 'Add volunteer',
    create: 'Create',
    week: 'Week',
    todo_list: 'To do list',
    completed: 'completed',
    create_task: 'Create task',
    my_volunteers: 'My volunteers',
    name: 'Name',
    modal_add_volunteer: 'Add a new volunteer',
    add_contacts: 'Choose from contact list',
    name_the_task: 'Name the task...',
    time: 'Time',
    details: 'Details',
    details_placeholder: 'Start typing here...',
    no_time: 'no time',
    exact_time: 'exact time',
    until: 'until',
    create_new_task: 'Create a new task',
    to_register: 'I want to register as a coordinator',
    share_with_family: 'Share with family',
    share_with_volunteer: 'Share with a volunteer',
    settings: 'Settings',
    language: 'language',
    logout: 'Logout',
    register: 'Register',
    share: 'Share',
    volunteer_create: 'Create volunteer',
    success: 'Success',
    toast_volunteer: 'Message sent to volunteers',
    will_do_this: 'will do this',
    free: 'free',
    back: 'Back',
    to_take: 'to take',
    task_completed: 'Task completed',
    delete_success: 'Delete was successful',
    username: 'Username',
    username_prompt: 'Login with which you can join the family',
    success_create_family: 'Family successfully created',
    profile_prompt: 'profile',
    main: 'main',
    coordinator: 'coordinator',
    to_volunteer_message: (family_name: string, link: string) =>
      `כידוע לכם משפחת ${family_name} צריכה עזרה בתקופה זו. ליחצו על הקישור, וביחרו את המשימות שבכוחכם לקחת  - ${link}
תודה רבה!`,
    to_family_message: (web_link: string, last_name: string, user_name: string, password: string) => `
    1. Follow the link ${web_link} and download the app
    2. Credentials to login: Username: ${user_name}. Password: ${password}. Join the family ${last_name}!`,
  },
  'he-IL': {
    email: 'אימייל',
    login_title: 'יד תמר',
    volunteer_create: 'צור מתנדב',
    password: 'סיסמה',
    login: 'התחברות',
    create_family: 'צור משפחה',
    welcome_text: 'ברוכים הבאים ל',
    my_families: 'המשפחות שלי',
    members_count: 'מתנדבים',
    last_name: 'שם משפחה',
    name_the_family: 'בחירת שם משפחה...',
    prompt_the_family: 'למשל: כהן',
    phone_number: 'מספר טלפון',
    volunteers: 'מתנדבים',
    add_volunteer: 'הוסף מתנדב',
    create: 'צור',
    week: 'השבוע',
    todo_list: 'רשימת מטלות',
    completed: 'בוצע',
    create_task: 'צור משימה',
    my_volunteers: 'המתנדבים שלי',
    name: 'שם',
    modal_add_volunteer: 'הוספת מתנדב חדש',
    add_contacts: 'בחר מרשימת אנשי קשר',
    name_the_task: 'שם המטלה…',
    time: 'זמן',
    details: 'פרטים',
    details_placeholder: 'הקלד כאן...',
    no_time: 'ללא ציון זמן',
    exact_time: 'זמן מדויק',
    until: 'עד לתאריך',
    create_new_task: 'צור משימה',
    profile: 'פרופיל',
    to_register: 'אני רוצה להירשם כרכז',
    share_with_family: 'שתף עם המשפחה',
    share_with_volunteer: 'שתף עם מתנדב',
    settings: 'הגדרות',
    language: 'שפה',
    logout: 'היתנתק',
    register: 'הירשם',
    share: 'לשתף',
    toast_volunteer: 'הודעה נשלחה למתנדבים',
    success: 'הצלחה',
    password_confirmation: 'אשר סיסמה',
    will_do_this: 'יעשה זאת',
    free: 'חינם',
    to_take: 'לקחת',
    back: 'חזור',
    task_completed: 'המשימה הושלמה',
    delete_success: 'ההסרה הצליחה',
    username: 'שם משתמש',
    username_prompt: 'בשם משתמש זה תוכל לבצע כניסה למשפחה',
    success_create_family: 'המשפחה נוצרה בהצלחה',
    profile_prompt: 'מסך ראשי',
    main: 'מלווה משפחה',
    coordinator: 'רכז',
    to_volunteer_message: (family_name: string, link: string) =>
      `כידוע לכם משפחת ${family_name} צריכה עזרה בתקופה זו. ליחצו על הקישור, וביחרו את המשימות שבכוחכם לקחת  - ${link}
תודה רבה!`,
    to_family_message: (web_link: string, last_name: string, user_name: string, password: string) => `
      שלום 
      כפי שידוע לך, משפחת ${last_name} תצטרך עזרה מיוחדת בצליחת התקופה הזו. 
      יש הרבה מאוד צרכים, וקל מאוד לטבוע במשימות. 
      מה שצריך עכשיו זה למפות את הצרכים, ואז לגייס את המשפחה המורחבת והקהילה לתת כתף. 
      יצרנו את Enola כדי להרחיב לתקופה קצרה את המשפחה. זו מערכת שהמטרה שלה היא למפות ולזהות את הצרכים המרובים של המשפחה ולאפשר למשפחה ולקהילה לתת כתף באופן יעיל.    
      לחיצה על הלינק תכניס אתכם למערכת ותאפשר לכם להתחיל במיפוי הצרכים. ככל שתהיו יותר ספצפיים, כך יהיה יותר קל למעגל המשפחתי לתת כתף.
      בכניסה הראשונית יש להזין את הפרטים הבאים:
      עקוב אחר הקישור: ${web_link} 
      שם משתמש: ${user_name}
      סיסמה: ${password}`,
  },
})

// ? Set the language manually
localStrings.setLanguage('he-IL')
