import LocalizedStrings from 'react-native-localization'

export const localStrings = new LocalizedStrings({
  en: {
    email: 'e-mail',
    login_title: 'Yad Tamar',
    password: 'password',
    password_confirmation: 'confirm password',
    profile: 'Profile',
    login: 'login',
    create_family: 'Create family',
    welcome_text: 'Welcome to',
    my_families: 'My families',
    members_count: 'members',
    name_the_family: 'Name the family',
    prompt_the_family: 'for example: Smith',
    phone_number: 'Phone number',
    last_name: 'Last name',
    volunteers: 'Volunteers',
    add_volunteer: 'Add volunteer',
    create: 'Create',
    week: 'Week',
    todo_list: 'To do list',
    completed: 'completed',
    create_task: 'Create task',
    my_volunteers: 'My volunteers',
    name: 'Name',
    modal_add_volunteer: 'Add a new volunteer',
    add_contacts: 'Choose from contact list',
    name_the_task: 'Name the task...',
    time: 'Time',
    details: 'Details',
    details_placeholder: 'Start typing here...',
    no_time: 'no time',
    exact_time: 'exact time',
    until: 'until',
    create_new_task: 'Create a new task',
    to_register: 'Don`t have an account? Sign up.',
    share_with_family: 'Share with family',
    share_with_volunteer: 'Share with a volunteer',
    settings: 'Settings',
    language: 'language',
    logout: 'Logout',
    register: 'Register',
    share: 'Share',
    volunteer_create: 'Create volunteer',
    success: 'Success',
    toast_volunteer: 'Message sent to volunteers',
    will_do_this: 'will do this',
    free: 'free',
    back: 'Back',
    to_take: 'to take',
    task_completed: 'Task completed',
    delete_success: 'Delete was successful',
    to_volunteer_message: (link: string) => `Enola. View your tasks on the link: ${link}`,
    to_family_message: (web_link: string, app_link: string) => `
    1. Follow the link ${web_link} and download the app
    2. After downloading click on this link: ${app_link} . Join the family!`,
  },
  heb: {
    email: 'אימייל',
    login_title: 'יד תמר',
    volunteer_create: 'צור מתנדב',
    password: 'סיסמה',
    login: 'התחברות',
    create_family: 'צור משפחה',
    welcome_text: 'ברוכים הבאים ל',
    my_families: 'המשפחות שלי',
    members_count: 'חברים',
    last_name: 'שֵׁם מִשׁפָּחָה',
    name_the_family: 'בחירת שם משפחה...',
    prompt_the_family: 'למשל: סמית',
    phone_number: 'מספר טלפון',
    volunteers: 'מתנדבים',
    add_volunteer: 'הוסף מתנדב',
    create: 'צור משפחה',
    week: 'השבוע',
    todo_list: 'רשימת מטלות',
    completed: 'רשימת מטלות',
    create_task: 'צור משימה',
    my_volunteers: 'המתנדבים שלי',
    name: 'שם',
    modal_add_volunteer: 'הוספת מתנדב חדש',
    add_contacts: 'בחר מרשימת אנשי קשר',
    name_the_task: 'שם המטלה…',
    time: 'זמן',
    details: 'פרטים',
    details_placeholder: 'הקלד כאן...',
    no_time: 'ללא ציון זמן',
    exact_time: 'זמן מדויק',
    until: 'עד לתאריך',
    create_new_task: 'כהן',
    profile: 'פּרוֹפִיל',
    to_register: 'אין לך חשבון? הירשם.',
    share_with_family: 'שתף עם המשפחה',
    share_with_volunteer: 'שתף עם מתנדב',
    settings: 'הגדרות',
    language: 'שפה',
    logout: 'להתנתק',
    register: 'הירשם',
    share: 'לשתף',
    toast_volunteer: 'הודעה נשלחה למתנדבים',
    success: 'הַצלָחָה',
    password_confirmation: 'אשר סיסמה',
    will_do_this: 'יעשה את זה',
    free: 'חינם',
    to_take: 'לקחת',
    back: 'חזור',
    task_completed: 'משימה הושלמה',
    delete_success: 'ההסרה הצליחה',
    to_volunteer_message: (link: string) => `Enola. View your tasks on the link: ${link}`,
    to_family_message: (web_link: string, app_link: string) => `
    1. Follow the link ${web_link} and download the app
    2. After downloading click on this link: ${app_link} . Join the family!`,
  },
})

// ? Set the language manually
localStrings.setLanguage('heb')
